#
# TODO: documentation
#
set(LINUX 1)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
SET(CMAKE_C_COMPILER x86_64-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER x86_64-linux-gnu-g++)
SET(CMAKE_RC_COMPILER x86_64-linux-gnu-windres)
set(CMAKE_RANLIB x86_64-linux-gnu-ranlib)
set(CMAKE_SKIP_BUILD_RPATH OFF)
set(CMAKE_BUILD_RPATH_USE_ORIGIN ON)
set(CMAKE_BUILD_WITH_INSTALL_RPATH OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

include(${CMAKE_CURRENT_LIST_DIR}/shared/gcc.cmake)
